# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.example.json', '.'),
    ],
    hiddenimports=[
        'animation', 'animation.clip', 'animation.layer',
        'animation.controller', 'animation.builtin',
        'ai', 'ai.doubao_api', 'ai.chat_dialog',
        'ai.memory_manager', 'ai.emotion_state',
        'winsdk', 'ctypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt6.Qt3DAnimation', 'PyQt6.Qt3DCore', 'PyQt6.Qt3DExtras',
        'PyQt6.Qt3DInput', 'PyQt6.Qt3DLogic', 'PyQt6.Qt3DRender',
        'PyQt6.QtBluetooth', 'PyQt6.QtCharts', 'PyQt6.QtDataVisualization',
        'PyQt6.QtDBus', 'PyQt6.QtDesigner', 'PyQt6.QtHelp',
        'PyQt6.QtMultimedia', 'PyQt6.QtMultimediaWidgets',
        'PyQt6.QtNfc', 'PyQt6.QtNetwork', 'PyQt6.QtOpenGL',
        'PyQt6.QtOpenGLWidgets', 'PyQt6.QtPdf', 'PyQt6.QtPdfWidgets',
        'PyQt6.QtPositioning', 'PyQt6.QtPrintSupport', 'PyQt6.QtQml',
        'PyQt6.QtQuick', 'PyQt6.QtQuick3D', 'PyQt6.QtQuickWidgets',
        'PyQt6.QtRemoteObjects', 'PyQt6.QtSensors', 'PyQt6.QtSerialPort',
        'PyQt6.QtSpatialAudio', 'PyQt6.QtSql', 'PyQt6.QtStateMachine',
        'PyQt6.QtSvg', 'PyQt6.QtSvgWidgets', 'PyQt6.QtTest',
        'PyQt6.QtTextToSpeech', 'PyQt6.QtWebChannel', 'PyQt6.QtWebEngine',
        'PyQt6.QtWebEngineCore', 'PyQt6.QtWebEngineQuick',
        'PyQt6.QtWebEngineWidgets', 'PyQt6.QtWebSockets', 'PyQt6.QtXml',
        'PyQt6.lupdate', 'PyQt6.pylupdate', 'PyQt6.uic',
        'winsdk.windows.ai', 'winsdk.windows.applicationmodel',
        'winsdk.windows.data', 'winsdk.windows.devices',
        'winsdk.windows.foundation', 'winsdk.windows.gaming',
        'winsdk.windows.globalization', 'winsdk.windows.graphics',
        'winsdk.windows.management', 'winsdk.windows.networking',
        'winsdk.windows.perception', 'winsdk.windows.phone',
        'winsdk.windows.security', 'winsdk.windows.services',
        'winsdk.windows.storage', 'winsdk.windows.system',
        'winsdk.windows.ui', 'winsdk.windows.web',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DesktopPet',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,
    disable_windowed_traceback=False,
)
